runtime: nodejs18  # Adjust this based on your Node.js version
service: default

env_variables:
  RUNTIME_ENDPOINT: "https://general-runtime.voiceflow.com"
  PROJECT_ID: "670051167305f4f9dfa409a7"
  API_KEY: "VF.DM.6704fc2164e59b16e562f2fa.QuN1SiPca01zgeS6"
  ENVIRONMENT: "production"
  ALLOWED_ORIGINS: "https://canopy.school,http://localhost"
